# Lumo UI Plugin
# This file is used to store configurations for the Lumo UI Plugin
# Do not delete this file

ThemeName=KomrdTheme
ComponentsDir=core/designsystem/src/main/kotlin/dev/komrd/core/designsystem
PackageName=dev.komrd.core.designsystem
# Uncomment this line if you are using Kotlin Multiplatform
# KotlinMultiplatform=false